#!/usr/bin/env python3
"""Render a class model (YAML plan or JSON as-built) to Mermaid classDiagram.

The model schema is shared by `class-plan.yaml` (authored, transient) and
`class-asbuilt.json` (generated by tools/arch/extract-classes). This tool only
renders; it never decides what is correct.

Usage:
    class_render.py --model class-asbuilt.json --out class.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml


def load_model(path: Path) -> dict:
    text = path.read_text()
    if path.suffix in (".yaml", ".yml"):
        return yaml.safe_load(text) or {}
    return json.loads(text)


def _type(raw: str) -> str:
    # Mermaid uses ~ where Rust uses angle brackets.
    return raw.replace("<", "~").replace(">", "~")


def _method(sig: str) -> str:
    if " -> " in sig:
        head, ret = sig.split(" -> ", 1)
        return f"{head} {_type(ret)}"
    return sig


def render(model: dict) -> str:
    lines = ["classDiagram", "    direction TB"]
    for cls in model.get("classes", []):
        lines.append(f"    class {cls['name']} {{")
        if cls.get("kind") and cls["kind"] != "class":
            lines.append(f"        <<{cls['kind']}>>")
        for variant in cls.get("variants", []):
            lines.append(f"        {variant}")
        for field in cls.get("fields", []):
            sign = "+" if field.get("visibility") == "public" else "-"
            lines.append(f"        {sign}{_type(field.get('type', ''))} {field['name']}")
        for method in cls.get("methods", []):
            sign = "+" if method.get("visibility") == "public" else "-"
            lines.append(f"        {sign}{_method(method.get('signature', method['name']))}")
        lines.append("    }")
    for rel in model.get("relations", []):
        arrow = "..|>" if rel["kind"] == "implementation" else "-->"
        label = f" : {rel['kind']}" if rel["kind"] != "composition" else ""
        lines.append(f"    {rel['from']} {arrow} {rel['to']}{label}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    rendered = render(load_model(args.model))
    if args.out:
        args.out.write_text(
            f"# Class Model: {load_model(args.model).get('context', 'unknown')} (as-built)\n\n"
            "<!-- GENERATED by tools/arch/class_render.py — do not edit by hand. -->\n\n"
            "```mermaid\n" + rendered + "```\n"
        )
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
