#!/usr/bin/env python3
"""Render a database model (JSON) to a Mermaid erDiagram.

This is the database counterpart of `class_render.py`. It only renders; it
never decides what is correct. The model is produced deterministically by
`extract_schema.py` from the adapter's DDL.

Usage:
    schema_render.py --model database-asbuilt.json --out database.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def load_model(path: Path) -> dict:
    return json.loads(path.read_text())


def render(model: dict) -> str:
    lines = ["erDiagram"]
    for table in model.get("tables", []):
        lines.append(f"    {table['name']} {{")
        for column in table.get("columns", []):
            if column.get("primary_key"):
                key = " PK"
            elif column.get("unique"):
                key = " UK"
            else:
                key = ""
            nullable = (
                ' "nullable"'
                if not column.get("not_null") and not column.get("primary_key")
                else ""
            )
            lines.append(
                f"        {column['type']} {column['name']}{key}{nullable}"
            )
        lines.append("    }")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    model = load_model(args.model)
    rendered = render(model)
    if args.out:
        args.out.write_text(
            f"# Database Model: {model.get('context', 'unknown')} (as-built)\n\n"
            "<!-- GENERATED by tools/arch/schema_render.py — do not edit by hand. -->\n\n"
            "```mermaid\n" + rendered + "```\n"
        )
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
