#!/usr/bin/env python3
"""Render the Alloy category catalog from the conformance oracle.

The category -> group mapping is owned by the app's lexicon relation oracle
(`app/lexicon/relations.py`, `CATEGORY_GROUPS`). The Alloy domain model is a
projection of it, delimited by `BEGIN/END alloy-catalog` markers so it can be
regenerated instead of hand-edited.

    render_alloy_catalog.py --spec architecture/expense_tracking/domain.als --check
    render_alloy_catalog.py --spec architecture/expense_tracking/domain.als --write

`--check` (default) exits 1 and prints the expected block when the model is
stale; `--write` updates it in place.

Exit codes: 0 current/applied, 1 stale, 2 config error.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

from relations_loader import load_relations

BEGIN = "// BEGIN alloy-catalog"
END = "// END alloy-catalog"
GROUPS = ["Periodic", "Occasional", "Daily"]


def render_block(category_groups: dict[str, str]) -> str:
    by_group: dict[str, list[str]] = defaultdict(list)
    for name, group in category_groups.items():
        if group not in GROUPS:
            print(f"render-alloy: error: unknown group {group!r}", file=sys.stderr)
            raise SystemExit(2)
        by_group[group].append("Cat_" + name.replace(" ", "_"))

    lines = [
        BEGIN + " (generated by tools/lexicon/render_alloy_catalog.py)",
        "// The full family catalog: each category belongs to exactly one group and the",
        "// mapping is fixed (never user data). Source of truth is the conformance oracle",
        "// `lexicon/relations.py::CATEGORY_GROUPS`. Do not edit by hand; run",
        "// `render_alloy_catalog.py --write`.",
    ]
    for group in GROUPS:
        sigs = ", ".join(sorted(by_group.get(group, [])))
        lines.append(f"one sig {sigs} extends Category {{}} {{ group = {group} }}")
    lines.append(END)
    return "\n".join(lines)


def splice(source: str, block: str) -> str:
    start = source.find(BEGIN)
    end = source.find(END)
    if start == -1 or end == -1 or end < start:
        print(
            "render-alloy: error: model has no BEGIN/END alloy-catalog markers",
            file=sys.stderr,
        )
        raise SystemExit(2)
    end += len(END)
    return source[:start] + block + source[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True, type=Path)
    parser.add_argument("--lexicon-dir", default="app/lexicon", type=Path)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="update the model in place")
    mode.add_argument("--check", action="store_true", help="fail if stale (default)")
    args = parser.parse_args()

    if not args.spec.exists():
        print(f"render-alloy: error: {args.spec} not found", file=sys.stderr)
        return 2

    source = args.spec.read_text()
    block = render_block(load_relations(args.lexicon_dir).CATEGORY_GROUPS)
    updated = splice(source, block)

    if args.write:
        if updated != source:
            args.spec.write_text(updated)
            print(f"render-alloy: updated {args.spec}")
        else:
            print(f"render-alloy: {args.spec} already current")
        return 0

    if updated != source:
        print(f"render-alloy: {args.spec} is stale; run:", file=sys.stderr)
        print(
            f"  python3 tools/lexicon/render_alloy_catalog.py --spec {args.spec} --write",
            file=sys.stderr,
        )
        print("\nexpected block:\n", file=sys.stderr)
        print(block, file=sys.stderr)
        return 1

    print(f"render-alloy: {args.spec} catalog is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())